/* eslint-disable react/jsx-key */
import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql,
} from "@apollo/client";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import MainFeaturedPost from "../components/MainFeaturedPost";
import Header from "../components/Header";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import Button from "@mui/material/Button";
import Modal from "@mui/material/Modal";
import CardContent from "@mui/material/CardContent";
import Box from "@mui/material/Box";

const client = new ApolloClient({
  uri: "https://practicedbapp.herokuapp.com/graphql",
  cache: new InMemoryCache(),
});

const sections = [
  { title: "Home", url: "/" },
  { title: "About", url: "#" },
  { title: "Personal Website", url: "https://www.samfletch.sbs/" },
];

const wowie = gql`
  query {
    allPosts(L: 1) {
      title
      subtitle
      publishDate
      image
      body
      author {
        username
      }
    }
  }
`;

function OlderPost() {
  const { loading, error, data } = useQuery(wowie);
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  const style = {
    position: "absolute" as "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    p: 4,
  };
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return data.allPosts.map(
    ({
      title,
      subtitle,
      publishDate,
      image,
      author,
      body,
    }: {
      publishDate: any;
      subtitle: any;
      title: any;
      image: any;
      author: any;
      body: any;
    }) => (
      <Grid item xs={12} md={6} sx={{ p: 2 }}>
        <Card sx={{ display: "flex" }}>
          <CardContent sx={{ flex: 1 }}>
            <Typography component="h2" variant="h5">
              {title}
            </Typography>
            <Typography variant="subtitle1" color="text.secondary">
              {publishDate}
            </Typography>
            <Typography variant="subtitle1" paragraph>
              {author.username}
            </Typography>
            <Typography variant="h5" paragraph sx={{ pt: 2 }}>
              {subtitle}
            </Typography>
            <CardActions>
              <Button variant="text" onClick={handleOpen}>
                Learn More
              </Button>
              <Modal
                open={open}
                onClose={handleClose}
                aria-labelledby="modal-modal-title"
                aria-describedby="modal-modal-description"
              >
                <Box sx={style}>
                  <Typography
                    id="modal-modal-title"
                    variant="h6"
                    component="h2"
                  >
                    {title}
                  </Typography>
                  <Typography id="modal-modal-description" sx={{ mt: 2 }}>
                    {body}
                  </Typography>
                </Box>
              </Modal>
            </CardActions>
          </CardContent>
          <Image src={image} alt="ewnigig" height={200} width={200} />
        </Card>
      </Grid>
    )
  );
}

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="/styles/kingsgmb.ttf"
            as="font"
            crossOrigin=""
          />
        </Head>

        <main className={styles.main}>
          <Header title="Samuel's Blog" sections={sections} />
          <div className={styles.flexy}>
            <MainFeaturedPost />
          </div>
          <div className={styles.flexs}>
            <OlderPost />
          </div>
        </main>
      </div>
    </ApolloProvider>
  );
};

export default Home;
