/* eslint-disable react/jsx-key */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql,
} from "@apollo/client";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import MainFeaturedPost from "../components/MainFeaturedPost";
import Header from "../components/Header";
import Card from "@mui/material/Card";
import CardActionArea from "@mui/material/CardActionArea";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
const client = new ApolloClient({
  uri: "https://practicedbapp.herokuapp.com/graphql",
  cache: new InMemoryCache(),
});

const sections = [
  { title: "Home", url: "/" },
  { title: "About", url: "#" },
  { title: "Personal Website", url: "https://www.samfletch.sbs/" },
];

const wowie = gql`
  query {
    allPosts(L: 1) {
      title
      subtitle
      publishDate
      image
    }
  }
  
`;

function OlderPost() {
  const { loading, error, data } = useQuery(wowie);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return data.allPosts.map(({ title,subtitle,publishDate, image }: { publishDate:any, subtitle:any, title: any; image: any }) => (
    <Grid item xs={12} md={6} sx={{ p: 2 }}>
      <CardActionArea component="a" href="#">
        <Card sx={{ display: "flex" }}>
          <CardContent sx={{ flex: 1 }}>
            <Typography component="h2" variant="h5">
              {title}
            </Typography>
            <Typography variant="subtitle1" color="text.secondary">
              {publishDate}
            </Typography>
            <Typography variant="subtitle1" paragraph>
              {subtitle}
            </Typography>
            <Typography variant="subtitle1" color="primary">
              Continue reading...
            </Typography>
          </CardContent>
          <Image src={image} alt="ewnigig" height={200} width={200} />
        </Card>
      </CardActionArea>
    </Grid>
  ));
}

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="/styles/kingsgmb.ttf"
            as="font"
            crossOrigin=""
          />
        </Head>

        <main className={styles.main}>
          <Header title="Samuel's Blog" sections={sections} />
          <div className={styles.flexy}>
            <MainFeaturedPost />
          </div>
          <div className={styles.flexs}>
            <OlderPost />
          </div>
        </main>
      </div>
    </ApolloProvider>
  );
};

export default Home;
